version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_password123! -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 60s

  app:
    build: .
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=MottuDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;"
    ports:
      - "5000:80"

volumes:
  mssqldata: