-- script_bd.sql
-- DDL para criar as tabelas usadas pela API (Azure SQL / SQL Server)

CREATE TABLE T_VM_AREA (
    ID_AREA INT IDENTITY(1,1) PRIMARY KEY,
    NM_AREA NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE T_VM_USUARIO (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NM_USUARIO NVARCHAR(100) NOT NULL,
    DS_EMAIL NVARCHAR(150) NOT NULL UNIQUE,
    DS_USERNAME NVARCHAR(60) NOT NULL UNIQUE,
    DS_PASSWORD_HASH NVARCHAR(2000) NOT NULL,
    DS_ROLE NVARCHAR(20) NOT NULL
);
GO

CREATE TABLE T_VM_MOTO (
    ID_MOTO INT IDENTITY(1,1) PRIMARY KEY,
    DS_PLACA NVARCHAR(20) NOT NULL,
    NM_MODELO NVARCHAR(100) NOT NULL,
    ID_AREA INT NOT NULL,
    CONSTRAINT FK_MOTO_AREA FOREIGN KEY (ID_AREA) REFERENCES T_VM_AREA(ID_AREA)
);
GO

-- Inserir pelo menos 2 registros reais na tabela T_VM_MOTO e 2 usuarios
INSERT INTO T_VM_AREA (NM_AREA) VALUES ('Centro'), ('Zona Leste');
GO

INSERT INTO T_VM_USUARIO (NM_USUARIO, DS_EMAIL, DS_USERNAME, DS_PASSWORD_HASH, DS_ROLE)
VALUES 
('Admin Demo', 'admin@example.com', 'admin', 'admin123', 'Admin'),
('Usuario Demo', 'user@example.com', 'user', 'user123', 'User');
GO

INSERT INTO T_VM_MOTO (DS_PLACA, NM_MODELO, ID_AREA)
VALUES
('ABC1D23', 'Honda CG 160', 1),
('ZXQ9Y88', 'Yamaha YBR 125', 2);
GO
